name: journal
description: Журнал ИП-152
publish_to: "none"
version: 2.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  flutter_launcher_icons: ^0.13.1
  http: ^1.2.0
  uuid: ^4.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
